/* =============================================================================
   40_kpi_dealer_kpi.sql
   DGPM_SPM — 經銷商KPI管理 / 系統資料查詢 / KPI資料權限（kpi schema）

   ⚠ PROVISIONAL DRAFT：SDS 尚未到位，以下為依 sitemap 推導的暫定設計，
     欄位名稱、型別、長度與約束皆可能在 SDS 定稿後調整，不得視為正式規格。

   對應 sitemap（頁面 → 資料表；查詢/流程頁重用既有表，不另建表）：
   - 經銷商KPI管理 / KPI指標設定       → kpi.KPI_INDICATOR
   - 經銷商KPI管理 / KPI數據匯入       → kpi.KPI_IMPORT_BATCH + kpi.KPI_DATA
   - 經銷商KPI管理 / KPI數據覆核與解鎖 → kpi.KPI_DATA.REVIEW_STATUS（流程欄位）
                                          + kpi.KPI_CHANGE_LOG（動作留痕）
   - 系統權限管理 / KPI資料權限管理    → kpi.KPI_USER_DATA_SCOPE
   - 系統資料查詢 / KPI異動紀錄查詢    → 重用 kpi.KPI_CHANGE_LOG
   - 系統資料查詢 / KPI匯入日誌查詢    → 重用 kpi.KPI_IMPORT_BATCH
   - 系統資料查詢 / 使用者登入軌跡查詢 → 重用 dbo.AUTHENTICATION_LOG
   - 經銷商儀錶板（Qlik Cloud）        → 外部整合，無核心業務表

   相依：00_create_schemas.sql、20_org_master_data.sql（org.DEALER）

   備註：USER_ID 欄位邏輯上對應 dbo.EMP_USER.USER_ID，但既有 QMS 表定義
   非本專案所有，為避免與既有 DB 型別不一致造成建立失敗，不建立跨界 FK，
   僅以文件標明邏輯關聯；SDS 定稿後再決定是否加實體 FK。
   ============================================================================= */

/* ---------- kpi.KPI_INDICATOR：KPI 指標定義 ---------- */
IF OBJECT_ID(N'kpi.KPI_INDICATOR', N'U') IS NULL
BEGIN
    CREATE TABLE kpi.KPI_INDICATOR
    (
        INDICATOR_ID   INT            IDENTITY(1,1) NOT NULL,
        INDICATOR_CODE NVARCHAR(30)   NOT NULL,  -- 業務代碼，穩定識別
        INDICATOR_NAME NVARCHAR(200)  NOT NULL,
        UNIT           NVARCHAR(20)   NULL,      -- 單位（台、%、金額…）
        DATA_TYPE      CHAR(1)        NOT NULL CONSTRAINT DF_KPI_INDICATOR_DATA_TYPE DEFAULT ('N'),  -- N=數值, P=百分比, A=金額
        DECIMAL_PLACES TINYINT        NOT NULL CONSTRAINT DF_KPI_INDICATOR_DECIMALS DEFAULT (2),
        SORT_ORDER     INT            NOT NULL CONSTRAINT DF_KPI_INDICATOR_SORT_ORDER DEFAULT (0),
        STATUS         CHAR(1)        NOT NULL CONSTRAINT DF_KPI_INDICATOR_STATUS DEFAULT ('A'),  -- A=啟用, I=停用
        MEMO           NVARCHAR(500)  NULL,
        CRT_DATE       DATETIME2(0)   NOT NULL CONSTRAINT DF_KPI_INDICATOR_CRT_DATE DEFAULT (SYSDATETIME()),
        CRT_USER       NVARCHAR(50)   NOT NULL,
        MDF_DATE       DATETIME2(0)   NULL,
        MDF_USER       NVARCHAR(50)   NULL,
        CONSTRAINT PK_KPI_INDICATOR PRIMARY KEY CLUSTERED (INDICATOR_ID),
        CONSTRAINT UQ_KPI_INDICATOR_CODE UNIQUE (INDICATOR_CODE),
        CONSTRAINT CK_KPI_INDICATOR_STATUS CHECK (STATUS IN ('A', 'I')),
        CONSTRAINT CK_KPI_INDICATOR_DATA_TYPE CHECK (DATA_TYPE IN ('N', 'P', 'A'))
    );
END
GO

/* ---------- kpi.KPI_IMPORT_BATCH：匯入批次（兼作匯入日誌） ---------- */
IF OBJECT_ID(N'kpi.KPI_IMPORT_BATCH', N'U') IS NULL
BEGIN
    CREATE TABLE kpi.KPI_IMPORT_BATCH
    (
        BATCH_ID      BIGINT         IDENTITY(1,1) NOT NULL,
        FILE_NAME     NVARCHAR(260)  NULL,      -- 來源檔名（Excel/CSV）
        PERIOD_YM     CHAR(6)        NOT NULL,  -- 匯入資料所屬年月 yyyyMM
        IMPORT_STATUS CHAR(1)        NOT NULL CONSTRAINT DF_KPI_IMPORT_BATCH_STATUS DEFAULT ('P'),  -- P=處理中, S=成功, F=失敗
        TOTAL_ROWS    INT            NOT NULL CONSTRAINT DF_KPI_IMPORT_BATCH_TOTAL DEFAULT (0),
        SUCCESS_ROWS  INT            NOT NULL CONSTRAINT DF_KPI_IMPORT_BATCH_SUCCESS DEFAULT (0),
        FAIL_ROWS     INT            NOT NULL CONSTRAINT DF_KPI_IMPORT_BATCH_FAIL DEFAULT (0),
        ERROR_MESSAGE NVARCHAR(MAX)  NULL,      -- 失敗摘要；不得含敏感資訊
        IMPORT_USER   NVARCHAR(50)   NOT NULL,  -- 邏輯對應 dbo.EMP_USER.USER_ID
        IMPORT_START  DATETIME2(0)   NOT NULL CONSTRAINT DF_KPI_IMPORT_BATCH_START DEFAULT (SYSDATETIME()),
        IMPORT_END    DATETIME2(0)   NULL,
        CONSTRAINT PK_KPI_IMPORT_BATCH PRIMARY KEY CLUSTERED (BATCH_ID),
        CONSTRAINT CK_KPI_IMPORT_BATCH_STATUS CHECK (IMPORT_STATUS IN ('P', 'S', 'F'))
    );

    CREATE NONCLUSTERED INDEX IX_KPI_IMPORT_BATCH_PERIOD
        ON kpi.KPI_IMPORT_BATCH (PERIOD_YM, IMPORT_START DESC);
END
GO

/* ---------- kpi.KPI_DATA：KPI 數據（經銷商 × 指標 × 年月） ---------- */
IF OBJECT_ID(N'kpi.KPI_DATA', N'U') IS NULL
BEGIN
    CREATE TABLE kpi.KPI_DATA
    (
        DATA_ID       BIGINT         IDENTITY(1,1) NOT NULL,
        DEALER_ID     INT            NOT NULL,
        INDICATOR_ID  INT            NOT NULL,
        PERIOD_YM     CHAR(6)        NOT NULL,  -- 資料年月 yyyyMM
        KPI_VALUE     DECIMAL(18,6)  NULL,
        BATCH_ID      BIGINT         NULL,      -- 最近一次寫入之匯入批次；手動修正可為 NULL
        REVIEW_STATUS CHAR(1)        NOT NULL CONSTRAINT DF_KPI_DATA_REVIEW_STATUS DEFAULT ('D'),
                                                -- D=草稿, R=覆核完成(鎖定), U=已解鎖待修正
        REVIEW_USER   NVARCHAR(50)   NULL,      -- 最近覆核/解鎖人，邏輯對應 dbo.EMP_USER.USER_ID
        REVIEW_DATE   DATETIME2(0)   NULL,
        CRT_DATE      DATETIME2(0)   NOT NULL CONSTRAINT DF_KPI_DATA_CRT_DATE DEFAULT (SYSDATETIME()),
        CRT_USER      NVARCHAR(50)   NOT NULL,
        MDF_DATE      DATETIME2(0)   NULL,
        MDF_USER      NVARCHAR(50)   NULL,
        CONSTRAINT PK_KPI_DATA PRIMARY KEY CLUSTERED (DATA_ID),
        CONSTRAINT UQ_KPI_DATA_DEALER_INDICATOR_YM UNIQUE (DEALER_ID, INDICATOR_ID, PERIOD_YM),
        CONSTRAINT FK_KPI_DATA_DEALER FOREIGN KEY (DEALER_ID) REFERENCES org.DEALER (DEALER_ID),
        CONSTRAINT FK_KPI_DATA_INDICATOR FOREIGN KEY (INDICATOR_ID) REFERENCES kpi.KPI_INDICATOR (INDICATOR_ID),
        CONSTRAINT FK_KPI_DATA_BATCH FOREIGN KEY (BATCH_ID) REFERENCES kpi.KPI_IMPORT_BATCH (BATCH_ID),
        CONSTRAINT CK_KPI_DATA_REVIEW_STATUS CHECK (REVIEW_STATUS IN ('D', 'R', 'U'))
    );

    CREATE NONCLUSTERED INDEX IX_KPI_DATA_PERIOD ON kpi.KPI_DATA (PERIOD_YM, DEALER_ID);
END
GO

/* ---------- kpi.KPI_CHANGE_LOG：KPI 異動紀錄（含覆核/解鎖留痕） ---------- */
IF OBJECT_ID(N'kpi.KPI_CHANGE_LOG', N'U') IS NULL
BEGIN
    CREATE TABLE kpi.KPI_CHANGE_LOG
    (
        LOG_ID      BIGINT         IDENTITY(1,1) NOT NULL,
        DATA_ID     BIGINT         NOT NULL,
        ACTION_TYPE CHAR(1)        NOT NULL,  -- I=匯入, M=修改, R=覆核, U=解鎖
        OLD_VALUE   DECIMAL(18,6)  NULL,
        NEW_VALUE   DECIMAL(18,6)  NULL,
        REASON      NVARCHAR(500)  NULL,      -- 修改/解鎖原因
        ACTION_USER NVARCHAR(50)   NOT NULL,  -- 邏輯對應 dbo.EMP_USER.USER_ID
        ACTION_DATE DATETIME2(0)   NOT NULL CONSTRAINT DF_KPI_CHANGE_LOG_DATE DEFAULT (SYSDATETIME()),
        CONSTRAINT PK_KPI_CHANGE_LOG PRIMARY KEY CLUSTERED (LOG_ID),
        CONSTRAINT FK_KPI_CHANGE_LOG_DATA FOREIGN KEY (DATA_ID) REFERENCES kpi.KPI_DATA (DATA_ID),
        CONSTRAINT CK_KPI_CHANGE_LOG_ACTION CHECK (ACTION_TYPE IN ('I', 'M', 'R', 'U'))
    );

    CREATE NONCLUSTERED INDEX IX_KPI_CHANGE_LOG_DATA
        ON kpi.KPI_CHANGE_LOG (DATA_ID, ACTION_DATE DESC);
END
GO

/* ---------- kpi.KPI_USER_DATA_SCOPE：KPI 資料權限（使用者可見範圍） ---------- */
IF OBJECT_ID(N'kpi.KPI_USER_DATA_SCOPE', N'U') IS NULL
BEGIN
    CREATE TABLE kpi.KPI_USER_DATA_SCOPE
    (
        SCOPE_ID   INT           IDENTITY(1,1) NOT NULL,
        USER_ID    NVARCHAR(50)  NOT NULL,  -- 邏輯對應 dbo.EMP_USER.USER_ID（不建跨界 FK）
        SCOPE_TYPE CHAR(1)       NOT NULL,  -- R=區域, D=經銷商
        REGION_ID  INT           NULL,      -- SCOPE_TYPE = 'R' 時必填
        DEALER_ID  INT           NULL,      -- SCOPE_TYPE = 'D' 時必填
        CRT_DATE   DATETIME2(0)  NOT NULL CONSTRAINT DF_KPI_USER_SCOPE_CRT_DATE DEFAULT (SYSDATETIME()),
        CRT_USER   NVARCHAR(50)  NOT NULL,
        CONSTRAINT PK_KPI_USER_DATA_SCOPE PRIMARY KEY CLUSTERED (SCOPE_ID),
        CONSTRAINT FK_KPI_USER_SCOPE_REGION FOREIGN KEY (REGION_ID) REFERENCES org.REGION (REGION_ID),
        CONSTRAINT FK_KPI_USER_SCOPE_DEALER FOREIGN KEY (DEALER_ID) REFERENCES org.DEALER (DEALER_ID),
        CONSTRAINT CK_KPI_USER_SCOPE_TYPE CHECK (SCOPE_TYPE IN ('R', 'D')),
        CONSTRAINT CK_KPI_USER_SCOPE_TARGET CHECK (
            (SCOPE_TYPE = 'R' AND REGION_ID IS NOT NULL AND DEALER_ID IS NULL) OR
            (SCOPE_TYPE = 'D' AND DEALER_ID IS NOT NULL AND REGION_ID IS NULL)
        )
    );

    CREATE UNIQUE NONCLUSTERED INDEX UQ_KPI_USER_SCOPE_REGION
        ON kpi.KPI_USER_DATA_SCOPE (USER_ID, REGION_ID) WHERE REGION_ID IS NOT NULL;

    CREATE UNIQUE NONCLUSTERED INDEX UQ_KPI_USER_SCOPE_DEALER
        ON kpi.KPI_USER_DATA_SCOPE (USER_ID, DEALER_ID) WHERE DEALER_ID IS NOT NULL;
END
GO
