/* =============================================================================
   10_dbo_pgm_tables.sql
   PGM — 依 BMW LIST（BMWv20260720）＋四份 SRS 建立資料表

   收錄表（LIST）：
     EMP_USER, EMP_ORG, DIM_ROLE, MAP_USER_ROLE,
     SET_FUNCTION, MAP_ROLE_FUNCTION,
     SET_PARAMITEM, SET_PARAM, CHANGE_PASSWORD_HISTORY,
     AUTHENTICATION_LOG（登入流程必要；非 BMW LIST）

   不實作：DIM_RIGHT、MAP_ROLE_RUNCTION（LIST 未收錄／SRS 未用）

   SET_FUNCTION：
     - 基底欄位依 BMW
     - 擴充 SysFun 語意欄位（PARENT_ID / ACTION_TYPE / IS_MENU / IS_ENABLED /
       FUN_DESC / ICON），表名維持 SET_FUNCTION（不以 SysFun 建表）

   EMP_USER.DPT_CODE：
     - 專案／SA 增補，關聯 EMP_ORG.DPT_CODE（nvarchar(10)，允許 NULL）
     - 建表順序：EMP_ORG 須先於 EMP_USER（含 FK）

   可重複執行（表不存在才建立；既有庫缺欄／缺 FK 則補）。

   SET_* 表名：T-SQL 保留字前綴，物件參考一律用方括號（dbo.[SET_FUNCTION]）。
   本檔為 UTF-8 BOM；SSMS 請以 UTF-8 開啟，勿當 Big5／系統預設編碼。
   ============================================================================= */

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

USE [PGM_DEV];
GO

/* ---------- EMP_ORG：組織單位資料檔（僅 DDL 預留，本階段無維護 UI） ---------- */
IF OBJECT_ID(N'dbo.EMP_ORG', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.EMP_ORG
    (
        DPT_CODE     NVARCHAR(10)   NOT NULL,
        DPT_NO       NVARCHAR(6)    NOT NULL,
        DPTCD_NAME   NVARCHAR(50)   NOT NULL,
        DPTCD_ENAME  NVARCHAR(200)  NULL,
        CODE_BOSS    NVARCHAR(10)   NOT NULL,
        DPT_LEVE     NVARCHAR(1)    NOT NULL,
        UPPER_DPT    NVARCHAR(6)    NOT NULL,
        CRT_DATE     DATETIME       NOT NULL,
        CRT_USER     NVARCHAR(50)   NOT NULL,
        MDF_DATE     DATETIME       NULL,
        MDF_USER     NVARCHAR(50)   NULL,
        CONSTRAINT PK_EMP_ORG PRIMARY KEY CLUSTERED (DPT_CODE)
    );
END
GO

/* ---------- EMP_USER：使用者帳號維護檔（Login／EMPSet） ---------- */
IF OBJECT_ID(N'dbo.EMP_USER', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.EMP_USER
    (
        USER_ID    VARCHAR(10)    NOT NULL,
        USER_NAME  NVARCHAR(100)  NOT NULL,
        DPT_CODE   NVARCHAR(10)   NULL,       -- 關聯 EMP_ORG；允許 NULL（種子可未填）
        PASSWORD   VARCHAR(500)   NOT NULL,  -- BCrypt hash
        EMAIL      NVARCHAR(255)  NULL,
        TELEPHONE  NVARCHAR(50)   NULL,
        DEL_FLG    BIT            NOT NULL CONSTRAINT DF_EMP_USER_DEL_FLG DEFAULT (0), -- 0活動 1停用
        CRT_DATE   DATETIME       NOT NULL,
        CRT_USER   NVARCHAR(10)   NOT NULL,
        MDF_DATE   DATETIME       NULL,
        MDF_USER   NVARCHAR(10)   NULL,
        CONSTRAINT PK_EMP_USER PRIMARY KEY CLUSTERED (USER_ID),
        CONSTRAINT FK_EMP_USER_EMP_ORG FOREIGN KEY (DPT_CODE)
            REFERENCES dbo.EMP_ORG (DPT_CODE)
    );
END
GO

/* ---------- 既有庫升級：補 EMP_USER.DPT_CODE 與 FK ---------- */
IF OBJECT_ID(N'dbo.EMP_USER', N'U') IS NOT NULL
   AND COL_LENGTH(N'dbo.EMP_USER', N'DPT_CODE') IS NULL
BEGIN
    ALTER TABLE dbo.EMP_USER ADD DPT_CODE NVARCHAR(10) NULL;
END
GO

IF OBJECT_ID(N'dbo.EMP_USER', N'U') IS NOT NULL
   AND OBJECT_ID(N'dbo.EMP_ORG', N'U') IS NOT NULL
   AND COL_LENGTH(N'dbo.EMP_USER', N'DPT_CODE') IS NOT NULL
   AND OBJECT_ID(N'dbo.FK_EMP_USER_EMP_ORG', N'F') IS NULL
BEGIN
    ALTER TABLE dbo.EMP_USER
        ADD CONSTRAINT FK_EMP_USER_EMP_ORG FOREIGN KEY (DPT_CODE)
            REFERENCES dbo.EMP_ORG (DPT_CODE);
END
GO

/* ---------- DIM_ROLE：角色維護主檔（EMPSet R／RoleFunctionSet R；IT 維護） ---------- */
IF OBJECT_ID(N'dbo.DIM_ROLE', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.DIM_ROLE
    (
        ROLE_ID      VARCHAR(30)    NOT NULL,
        ROLE_NAME    NVARCHAR(50)   NOT NULL,
        SYSTEM_CODE  VARCHAR(20)    NOT NULL CONSTRAINT DF_DIM_ROLE_SYSTEM_CODE DEFAULT ('PGM'),
        DEL_FLG      BIT            NOT NULL CONSTRAINT DF_DIM_ROLE_DEL_FLG DEFAULT (0),
        CRT_DATE     DATETIME       NOT NULL,
        CRT_USER     NVARCHAR(10)   NOT NULL,
        MDF_DATE     DATETIME       NULL,
        MDF_USER     NVARCHAR(10)   NULL,
        CONSTRAINT PK_DIM_ROLE PRIMARY KEY CLUSTERED (ROLE_ID)
    );

    CREATE NONCLUSTERED INDEX IX_DIM_ROLE_SYSTEM_CODE
        ON dbo.DIM_ROLE (SYSTEM_CODE, DEL_FLG, ROLE_ID);
END
GO

/* 既有庫：補 SYSTEM_CODE（亦見 20_dbo_system_code.sql） */
IF OBJECT_ID(N'dbo.DIM_ROLE', N'U') IS NOT NULL
   AND COL_LENGTH(N'dbo.DIM_ROLE', N'SYSTEM_CODE') IS NULL
BEGIN
    ALTER TABLE dbo.DIM_ROLE ADD SYSTEM_CODE VARCHAR(20) NOT NULL
        CONSTRAINT DF_DIM_ROLE_SYSTEM_CODE DEFAULT ('PGM');
END
GO

/* ---------- MAP_USER_ROLE：人員角色對應檔 ---------- */
IF OBJECT_ID(N'dbo.MAP_USER_ROLE', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.MAP_USER_ROLE
    (
        USER_ID   VARCHAR(10)   NOT NULL,
        ROLE_ID   VARCHAR(30)   NOT NULL,
        CRT_DATE  DATETIME      NOT NULL,
        CRT_USER  NVARCHAR(10)  NOT NULL,
        CONSTRAINT PK_MAP_USER_ROLE PRIMARY KEY CLUSTERED (USER_ID, ROLE_ID)
    );
END
GO

/* ---------- SET_FUNCTION：功能主檔（BMW + SysFun 擴充欄；取代 SysFun 表） ---------- */
IF OBJECT_ID(N'dbo.SET_FUNCTION', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.[SET_FUNCTION]
    (
        /* BMW 基底 */
        FUNCTION_ID    VARCHAR(20)     NOT NULL,
        FUNCTION_NAME  NVARCHAR(50)    NOT NULL,
        FUNCTION_URL   NVARCHAR(100)   NULL,
        PARENT_NAME    VARCHAR(20)     NULL,   -- 大類顯示名（SRS Login 選單用）
        SORT_ID        SMALLINT        NOT NULL CONSTRAINT DF_SET_FUNCTION_SORT_ID DEFAULT (0),
        DEL_FLG        BIT             NOT NULL CONSTRAINT DF_SET_FUNCTION_DEL_FLG DEFAULT (0),
        CRT_DATE       DATETIME        NOT NULL,
        CRT_USER       NVARCHAR(10)    NOT NULL,
        MDF_DATE       DATETIME        NULL,
        MDF_USER       NVARCHAR(10)    NULL,

        /* SysFun 擴充（階層／選單語意；表名仍為 SET_FUNCTION） */
        PARENT_ID      VARCHAR(20)     NULL,   -- 上層 FUNCTION_ID；模組列為 NULL
        ACTION_TYPE    CHAR(1)         NOT NULL CONSTRAINT DF_SET_FUNCTION_ACTION_TYPE DEFAULT ('P'),
        IS_MENU        CHAR(1)         NOT NULL CONSTRAINT DF_SET_FUNCTION_IS_MENU DEFAULT ('N'),
        IS_ENABLED     CHAR(1)         NOT NULL CONSTRAINT DF_SET_FUNCTION_IS_ENABLED DEFAULT ('Y'),
        FUN_DESC       NVARCHAR(500)   NULL,
        ICON           NVARCHAR(50)    NULL,
        SYSTEM_CODE    VARCHAR(20)     NOT NULL CONSTRAINT DF_SET_FUNCTION_SYSTEM_CODE DEFAULT ('PGM'),

        CONSTRAINT PK_SET_FUNCTION PRIMARY KEY CLUSTERED (FUNCTION_ID),
        CONSTRAINT CK_SET_FUNCTION_ACTION_TYPE CHECK (ACTION_TYPE IN ('M', 'P', 'B')),
        CONSTRAINT CK_SET_FUNCTION_IS_MENU CHECK (IS_MENU IN ('Y', 'N')),
        CONSTRAINT CK_SET_FUNCTION_IS_ENABLED CHECK (IS_ENABLED IN ('Y', 'N'))
    );

    CREATE NONCLUSTERED INDEX IX_SET_FUNCTION_PARENT_SORT
        ON dbo.[SET_FUNCTION] (PARENT_ID, SORT_ID, FUNCTION_ID)
        WHERE DEL_FLG = 0;

    CREATE NONCLUSTERED INDEX IX_SET_FUNCTION_MENU
        ON dbo.[SET_FUNCTION] (SORT_ID, FUNCTION_ID)
        WHERE DEL_FLG = 0 AND IS_MENU = 'Y' AND IS_ENABLED = 'Y';

    CREATE NONCLUSTERED INDEX IX_SET_FUNCTION_SYSTEM_CODE
        ON dbo.[SET_FUNCTION] (SYSTEM_CODE, DEL_FLG, IS_MENU, IS_ENABLED, SORT_ID, FUNCTION_ID);
END
GO

IF OBJECT_ID(N'dbo.[SET_FUNCTION]', N'U') IS NOT NULL
   AND COL_LENGTH(N'dbo.[SET_FUNCTION]', N'SYSTEM_CODE') IS NULL
BEGIN
    ALTER TABLE dbo.[SET_FUNCTION] ADD SYSTEM_CODE VARCHAR(20) NOT NULL
        CONSTRAINT DF_SET_FUNCTION_SYSTEM_CODE DEFAULT ('PGM');
END
GO

/* ---------- MAP_ROLE_FUNCTION：功能角色對應檔（RoleFunctionSet／Login 選單） ---------- */
IF OBJECT_ID(N'dbo.MAP_ROLE_FUNCTION', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.MAP_ROLE_FUNCTION
    (
        ROLE_ID      VARCHAR(30)   NOT NULL,
        FUNCTION_ID  VARCHAR(20)   NOT NULL,
        CRT_DATE     DATETIME      NOT NULL,
        CRT_USER     NVARCHAR(10)  NOT NULL,
        CONSTRAINT PK_MAP_ROLE_FUNCTION PRIMARY KEY CLUSTERED (ROLE_ID, FUNCTION_ID)
    );
END
GO

/* ---------- SET_PARAMITEM：參數類資料檔（ParamSet：IT 維護，畫面 R） ---------- */
IF OBJECT_ID(N'dbo.SET_PARAMITEM', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.[SET_PARAMITEM]
    (
        SET_ITEM       NVARCHAR(50)   NOT NULL,
        SET_ITEM_NAME  NVARCHAR(20)   NOT NULL,
        MEMO           NVARCHAR(500)  NOT NULL,
        DEL_FLG        BIT            NOT NULL CONSTRAINT DF_SET_PARAMITEM_DEL_FLG DEFAULT (0),
        CRT_DATE       DATETIME       NOT NULL,
        CRT_USER       NVARCHAR(50)   NOT NULL,
        MDF_DATE       DATETIME       NULL,
        MDF_USER       NVARCHAR(50)   NULL,
        CONSTRAINT PK_SET_PARAMITEM PRIMARY KEY CLUSTERED (SET_ITEM)
    );
END
GO

/* ---------- SET_PARAM：參數類主檔細項檔（ParamSet CRUD） ---------- */
IF OBJECT_ID(N'dbo.SET_PARAM', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.[SET_PARAM]
    (
        SET_ITEM    NVARCHAR(50)   NOT NULL,
        SET_ID      NVARCHAR(20)   NOT NULL,
        SET_VALUE   NVARCHAR(50)   NOT NULL,
        SORT_ORDER  INT            NOT NULL CONSTRAINT DF_SET_PARAM_SORT_ORDER DEFAULT (0),
        MEMO        NVARCHAR(500)  NULL,
        DEL_FLG     BIT            NOT NULL CONSTRAINT DF_SET_PARAM_DEL_FLG DEFAULT (0),
        CRT_DATE    DATETIME       NOT NULL,
        CRT_USER    NVARCHAR(50)   NOT NULL,
        MDF_DATE    DATETIME       NULL,
        MDF_USER    NVARCHAR(50)   NULL,
        CONSTRAINT PK_SET_PARAM PRIMARY KEY CLUSTERED (SET_ITEM, SET_ID)
    );
END
GO

/* ---------- CHANGE_PASSWORD_HISTORY：變更／重設密碼記錄（Login） ---------- */
IF OBJECT_ID(N'dbo.CHANGE_PASSWORD_HISTORY', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.CHANGE_PASSWORD_HISTORY
    (
        LOG_ID    BIGINT         IDENTITY(1,1) NOT NULL,
        USER_ID   VARCHAR(10)    NOT NULL,
        PASSWORD  VARCHAR(500)   NOT NULL,  -- 新密碼 hash
        LOG_DATE  DATE           NOT NULL,
        CONSTRAINT PK_CHANGE_PASSWORD_HISTORY PRIMARY KEY CLUSTERED (LOG_ID)
    );

    CREATE NONCLUSTERED INDEX IX_CHANGE_PASSWORD_HISTORY_USER
        ON dbo.CHANGE_PASSWORD_HISTORY (USER_ID, LOG_DATE DESC);
END
GO

/* ---------- AUTHENTICATION_LOG：登入／登出軌跡（非 BMW LIST；Login 流程必要） ---------- */
IF OBJECT_ID(N'dbo.AUTHENTICATION_LOG', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.AUTHENTICATION_LOG
    (
        GUID              VARCHAR(36)    NOT NULL,
        USER_ID           VARCHAR(10)    NOT NULL,
        IDENTITY_CONTENT  NVARCHAR(500)  NULL,
        IP                NVARCHAR(50)   NULL,
        LOGIN_TYPE        CHAR(1)        NOT NULL,
        AUTH_STATUS       CHAR(1)        NOT NULL,
        LOGIN_TIME        DATETIME       NOT NULL,
        LOGOUT_TIME       DATETIME       NULL,
        CONSTRAINT PK_AUTHENTICATION_LOG PRIMARY KEY CLUSTERED (GUID)
    );

    CREATE NONCLUSTERED INDEX IX_AUTHENTICATION_LOG_USER_TIME
        ON dbo.AUTHENTICATION_LOG (USER_ID, LOGIN_TIME DESC);
END
GO

PRINT N'10_dbo_pgm_tables.sql completed: BMW LIST tables + EMP_USER.DPT_CODE FK + extended SET_FUNCTION + AUTHENTICATION_LOG.';
GO
