/* =============================================================================
   20_dbo_system_code.sql
   PGM Phase 3 — 為 DIM_ROLE／SET_FUNCTION 增加 SYSTEM_CODE（可重複執行）

   常數：PGM（平台管理）、DGPM（業務系統）
   既有列預設補 'PGM'。

   注意：必須在目標庫執行（預設 PGM_DEV）。若 SSMS 連到 master，
   本腳本不會改到 PGM_DEV，後續 90 會報「無效的資料行名稱 SYSTEM_CODE」。
   ============================================================================= */

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

USE [PGM_DEV];
GO

IF OBJECT_ID(N'dbo.DIM_ROLE', N'U') IS NOT NULL
   AND COL_LENGTH(N'dbo.DIM_ROLE', N'SYSTEM_CODE') IS NULL
BEGIN
    ALTER TABLE dbo.DIM_ROLE ADD SYSTEM_CODE VARCHAR(20) NOT NULL
        CONSTRAINT DF_DIM_ROLE_SYSTEM_CODE DEFAULT ('PGM');
END
GO

IF OBJECT_ID(N'dbo.DIM_ROLE', N'U') IS NOT NULL
   AND COL_LENGTH(N'dbo.DIM_ROLE', N'SYSTEM_CODE') IS NOT NULL
   AND NOT EXISTS (
        SELECT 1 FROM sys.indexes
        WHERE name = N'IX_DIM_ROLE_SYSTEM_CODE' AND object_id = OBJECT_ID(N'dbo.DIM_ROLE'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_DIM_ROLE_SYSTEM_CODE
        ON dbo.DIM_ROLE (SYSTEM_CODE, DEL_FLG, ROLE_ID);
END
GO

IF OBJECT_ID(N'dbo.[SET_FUNCTION]', N'U') IS NOT NULL
   AND COL_LENGTH(N'dbo.[SET_FUNCTION]', N'SYSTEM_CODE') IS NULL
BEGIN
    ALTER TABLE dbo.[SET_FUNCTION] ADD SYSTEM_CODE VARCHAR(20) NOT NULL
        CONSTRAINT DF_SET_FUNCTION_SYSTEM_CODE DEFAULT ('PGM');
END
GO

IF OBJECT_ID(N'dbo.[SET_FUNCTION]', N'U') IS NOT NULL
   AND COL_LENGTH(N'dbo.[SET_FUNCTION]', N'SYSTEM_CODE') IS NOT NULL
   AND NOT EXISTS (
        SELECT 1 FROM sys.indexes
        WHERE name = N'IX_SET_FUNCTION_SYSTEM_CODE' AND object_id = OBJECT_ID(N'dbo.[SET_FUNCTION]'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_SET_FUNCTION_SYSTEM_CODE
        ON dbo.[SET_FUNCTION] (SYSTEM_CODE, DEL_FLG, IS_MENU, IS_ENABLED, SORT_ID, FUNCTION_ID);
END
GO
